config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "recipes#index"
  resources :lookups, only: [:new, :create]
  resources :recipes, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    url = lookup_params.fetch(:url)
    response = HTTParty.get(url)
    page = Nokogiri::HTML(response.body)
    title = page.css("meta[property='og:title']").first.attributes["content"].value
    desc = page.css("meta[property='og:description']").first.attributes["content"].value
    image_url = page.css("meta[property='og:image']").first.attributes["content"].value

    redirect_to new_recipe_path(title: title, description: desc, image_url: image_url, url: url)
  end

  private

  def lookup_params
    params.require(:lookup).permit(:url)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = if params[:query].present?
      current_user.recipes.where("title ILIKE ? OR description ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    else
      current_user.recipes
    end
  end

  def new
    @recipe = current_user.recipes.build(
      title: params[:title],
      description: params[:description],
      image_url: params[:image_url],
      url: params[:url]
    )
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:url, :title, :description, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |flash_type, message| %>
  <div clas="mx-auto sm:w-3/4 md:w-2/4 fixed inset-x-0 top-1">
    <% if flash_type == "alert" %>
      <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:text-red-400 text-center" role="alert">
        <span class="font-medium"><%= message %></span>
      </div>
    <% else %>
      <div class="p-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:text-blue-400 text-center" role="alert">
        <span class="font-medium"><%= message %></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeSaver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
    <%= render "layouts/flash_messages" %>
    <nav class="bg-white border-b border-gray-200 text-sm font-medium">
      <div class="mx-auto container flex flex-wrap items-center justify-between p-4">
        <%= link_to "RecipeSaver", root_path, class: "font-medium text-xl" %>
        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn-secondary" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
    </nav>
    <main class="container mx-auto my-6 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeSaver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
    <%= render "layouts/flash_messages" %>
    <main class="container mx-auto flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lookups/new.html.erb
<div class="bg-gray-100 flex flex-col justify-center sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with url: lookups_path, scope: :lookup do |form| %>
        <div class="space-y-12">
          <h2 class="text-base font-semibold leading-7 text-gray-900">Add recipe</h2>
          <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
            <div class="col-span-full">
              <%= form.label :url,
              "Link",
              class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                  <%= form.text_field :url,
                  class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
          <%= link_to "Cancel", recipes_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
          <%= form.submit "Save", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="bg-gray-100 flex flex-col justify-center sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with model: @recipe do |form| %>
        <div class="space-y-12">
          <h2 class="text-base font-semibold leading-7 text-gray-900">Add recipe</h2>
          <div class="mt-4 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
            <div class="col-span-full">
              <%= form.label :title,
              "Title",
              class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                  <%= form.text_field :title,
                  class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
                </div>
              </div>
            </div>
            <div class="col-span-full">
              <%= form.hidden_field :image_url %>
              <%= image_tag @recipe.image_url, class: "w-full object-cover aspect-square", alt: "" %>
            </div>
            <div class="col-span-full">
              <%= form.label :description,
              "Description",
              class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                  <%= form.text_area :description,
                  class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
                </div>
              </div>
            </div>
            <div class="col-span-full">
              <%= form.label :url,
              "URL",
              class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                  <%= form.url_field :url,
                  class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-6 flex items-center justify-end gap-x-6">
          <%= link_to "Cancel", recipes_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
          <%= form.submit "Save", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="flex flex-wrap sm:flex-nowrap gap-4 p-4 rounded-md shadow bg-white hover:bg-gray-50 group">
  <div class="shrink-0">
    <%= image_tag recipe.image_url, class: "h-24 w-24 object-contain rounded-lg" %>
  </div>
  <div class="flex-1">
    <%= link_to recipe.url, target: :_blank, class: "flex flex-col h-full" do %>
      <div class="grow-1">
        <h2 class="text-xl font-semibold text-gray-800 hover:underline"><%= recipe.title %></h2>
        <p class="text-sm text-gray-600"><%= recipe.description %></p>
      </div>
      <p class="text-sm text-gray-500 truncate hover:underline mt-auto"><%= recipe.url %></p>
    <% end %>
  </div>
  <div class="shrink-0">
    <div class="flex-col hidden group-hover:flex  justify-between h-full">
      <%= link_to edit_recipe_path(recipe) do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 hover:opacity-50">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
        </svg>
      <% end %>
      <%= button_to recipe_path(recipe), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 hover:opacity-50">
          <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render "form" %>

app/views/recipes/index.html.erb
<div>
  <div class="flex gap-2 mb-14">
    <div class="flex-1">
      <%= form_with url: recipes_path, method: :get do |form| %>
        <%= form.label "Search", :query, class: "mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white" %>
        <div class="relative">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
          </div>
          <%= form.text_field :query, class: "block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-white-500 focus:ring-indigo-500 focus:border-indigo-500", placeholder: "Search for a recipe..." %>
        </div>
      <% end %>
    </div>
    <%= link_to "Add",
        new_lookup_path,
        class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 inline-flex items-center" %>
  </div>
  <ul class="space-y-4">
    <% @recipes.each do |recipe| %>
      <li><%= render recipe %></li>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<%= form_with model: @recipe do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name %>
  <%= form.label :url, "Link" %>
  <%= form.text_field :url %>
  <%= form.submit "Save" %>
<% end %>